# Generated by Django 5.1.4 on 2025-01-11 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_image', models.ImageField(upload_to='uploads/source_images/')),
                ('target_image', models.ImageField(upload_to='uploads/target_images/')),
                ('output_image', models.ImageField(blank=True, null=True, upload_to='uploads/output_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing', to='image_processor.uploadedimage')),
            ],
        ),
    ]
