# Generated by Django 5.1.4 on 2025-01-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0002_alter_uploadedimage_output_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='output_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/image_processor/enhanced_images/'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='source_image',
            field=models.ImageField(upload_to='media/image_processor/source_images/'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='target_image',
            field=models.ImageField(upload_to='media/image_processor/target_images/'),
        ),
    ]
